version: '3.8'
services:
  handshake:
    container_name: handshake
    restart: always
    image: postgres:13.4-alpine
    environment:
      - POSTGRES_PASSWORD=$DATABASE_PASSWORD
      - POSTGRES_USER=$DATABASE_USERNAME
      - POSTGRES_DB=$DATABASE_NAME
    ports:
      - $DATABASE_PORT:5432
    volumes:
      - ./.data_storage/postgres:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
networks:
  handshake:
    driver: bridge
    ipam:
      driver: default
