export const PIECE_OF_CAKE = 'PIECE_OF_CAKE';

export const CONTRACT_STATUS = {
  NEW: 'NEW',
  ON_PROCESS: 'ON_PROCESS',
  SUBMITTED: 'SUBMITTED',
  DONE: 'DONE',
  UN_COMPLETE: 'UN_COMPLETE',
  REPORT: 'REPORT',
};
